# Generated by Django 4.2.19 on 2025-02-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(help_text='(e.g., JSS1, JSS2, SSS1, SSS2)', max_length=100, unique=True),
        ),
    ]
