# Generated by Django 4.2.19 on 2025-02-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0002_alter_schoolclass_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('About', 'About'), ('Contact', 'Contact')], max_length=20, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
