# Generated by Django 4.2.19 on 2025-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0003_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalWelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('principal_name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='principal_pictures/')),
            ],
            options={
                'verbose_name': 'Principal Welcome Message',
                'verbose_name_plural': 'Principal Welcome Message',
            },
        ),
    ]
