# Generated by Django 4.2.19 on 2025-02-14 12:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0004_principalwelcomemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Footer Data',
                'verbose_name_plural': 'Footer Data',
            },
        ),
        migrations.AlterField(
            model_name='principalwelcomemessage',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
