# Generated by Django 4.2.19 on 2025-02-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0005_footerdata_alter_principalwelcomemessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerdata',
            name='copyright_text',
        ),
    ]
