# Generated by Django 4.2.19 on 2025-02-14 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0007_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_picture',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Main image (720x400)', upload_to='events/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='optional_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='optional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='optional_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
