# Generated by Django 4.2.19 on 2025-02-14 13:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0008_event_display_picture_event_optional_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
