# Generated by Django 4.2.19 on 2025-02-14 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0010_academicevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='academicevent',
            name='image',
        ),
        migrations.AddField(
            model_name='academicevent',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicevent',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
