# Generated by Django 4.2.19 on 2025-02-14 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0011_remove_academicevent_date_remove_academicevent_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicevent',
            name='start_date',
        ),
        migrations.AddField(
            model_name='academicevent',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicevent',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
