# Generated by Django 4.2.19 on 2025-02-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0012_remove_academicevent_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicevent',
            name='description',
            field=models.TextField(max_length=30),
        ),
    ]
