# Generated by Django 4.2.19 on 2025-02-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0016_subjecttaught_remove_topic_subject_delete_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttaught',
            name='school_class',
        ),
        migrations.AddField(
            model_name='subjecttaught',
            name='school_class',
            field=models.ManyToManyField(related_name='subjects', to='school_website.schoolclass'),
        ),
    ]
