# Generated by Django 4.2.19 on 2025-02-14 17:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0017_remove_subjecttaught_school_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttaught',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
