# Generated by Django 4.2.19 on 2025-02-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0018_alter_subjecttaught_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kindergarten', 'Kindergarten Education'), ('nursery', 'Nursery Education'), ('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('islamiyya', 'Islamiyya Education'), ('nexora_digital', 'Nexora Digital Academy')], max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjecttaught',
            name='school_class',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
        migrations.DeleteModel(
            name='SubjectTaught',
        ),
        migrations.AddField(
            model_name='curriculumoffer',
            name='subjects',
            field=models.ManyToManyField(related_name='curriculums', to='school_website.subject'),
        ),
    ]
