# Generated by Django 4.2.19 on 2025-02-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0020_alter_curriculumoffer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
