# Generated by Django 4.2.19 on 2025-02-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0024_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=250),
        ),
    ]
