# Generated by Django 4.2.19 on 2025-02-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website', '0026_aboutpage_delete_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Pages'},
        ),
    ]
